# Site settings
title: Hunting Stories
description: "A collection of adventures in the outdoors"
url: "https://jae0029.github.io"  # your GitHub Pages URL
baseurl: "/Hunting"               # repository name if using project page; "" if using user page

# Build settings
markdown: kramdow
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Permalinks
permalink: /:categories/:title/

# Author info (optional)
author:
  name: Joshua Etherton

# Exclude these files/folders from build
exclude:
  - README.md
  - node_modules
  - Gemfile
  - Gemfile.lock

# Optional defaults for posts
defaults:
  - scope:
      path: ""       # all files
      type: "posts"
    values:
      layout: post
      author: Joshua Etherton

collections:
  deer-hunts:
    output: true
    permalink: /deer-hunts/:title/
  turkey-hunts:
    output: true
    permalink: /turkey-hunts/:title/
  fishing:
    output: true
    permalink: /fishing/:title/
  other-stories:
    output: true
    permalink: /other-stories/:title/
  gallery:
    output: true
    permalink: /gallery/:title/
